server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_service_db?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hak
    password: hak

mybatis:
  type-aliases-package:
  mapper-locations: /mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true